#ifndef CLASS_ID_H
#define CLASS_ID_H


enum Class_id
{
    CLASS_ELEMENT,
    CLASS_KAMIEN,
    CLASS_KRYSZTAL,
    CLASS_PATYK,
    CLASS_MLOTEK,
    CLASS_NOZ,
    CLASS_SIEKIERA,
    CLASS_GLOWKA_MLOTKA,
    CLASS_OSTRZE_NOZA,
    CLASS_OSTRZE_SIEKIERY,
    CLASS_RACZKA_MLOTKA,
    CLASS_RACZKA_NOZA,
    CLASS_RACZKA_SIEKIERY,
    CLASS_WODA,
    CLASS_COUNT,
};

#endif // CLASS_NAME_H
